// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Requisicao struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Conteudo:
	//
	//	*Requisicao_Auth
	//	*Requisicao_Operacao
	Conteudo      isRequisicao_Conteudo `protobuf_oneof:"conteudo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requisicao) Reset() {
	*x = Requisicao{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requisicao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requisicao) ProtoMessage() {}

func (x *Requisicao) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requisicao.ProtoReflect.Descriptor instead.
func (*Requisicao) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *Requisicao) GetConteudo() isRequisicao_Conteudo {
	if x != nil {
		return x.Conteudo
	}
	return nil
}

func (x *Requisicao) GetAuth() *Auth {
	if x != nil {
		if x, ok := x.Conteudo.(*Requisicao_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *Requisicao) GetOperacao() *Operacao {
	if x != nil {
		if x, ok := x.Conteudo.(*Requisicao_Operacao); ok {
			return x.Operacao
		}
	}
	return nil
}

type isRequisicao_Conteudo interface {
	isRequisicao_Conteudo()
}

type Requisicao_Auth struct {
	Auth *Auth `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type Requisicao_Operacao struct {
	Operacao *Operacao `protobuf:"bytes,2,opt,name=operacao,proto3,oneof"`
}

func (*Requisicao_Auth) isRequisicao_Conteudo() {}

func (*Requisicao_Operacao) isRequisicao_Conteudo() {}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlunoId       string                 `protobuf:"bytes,1,opt,name=aluno_id,json=alunoId,proto3" json:"aluno_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetAlunoId() string {
	if x != nil {
		return x.AlunoId
	}
	return ""
}

func (x *Auth) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Operacao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	NomeOperacao  string                 `protobuf:"bytes,2,opt,name=nome_operacao,json=nomeOperacao,proto3" json:"nome_operacao,omitempty"`
	Parametros    map[string]string      `protobuf:"bytes,3,rep,name=parametros,proto3" json:"parametros,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operacao) Reset() {
	*x = Operacao{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operacao) ProtoMessage() {}

func (x *Operacao) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operacao.ProtoReflect.Descriptor instead.
func (*Operacao) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *Operacao) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Operacao) GetNomeOperacao() string {
	if x != nil {
		return x.NomeOperacao
	}
	return ""
}

func (x *Operacao) GetParametros() map[string]string {
	if x != nil {
		return x.Parametros
	}
	return nil
}

func (x *Operacao) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Resposta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operacao      *OperacaoResponse      `protobuf:"bytes,1,opt,name=operacao,proto3" json:"operacao,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resposta) Reset() {
	*x = Resposta{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resposta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resposta) ProtoMessage() {}

func (x *Resposta) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resposta.ProtoReflect.Descriptor instead.
func (*Resposta) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *Resposta) GetOperacao() *OperacaoResponse {
	if x != nil {
		return x.Operacao
	}
	return nil
}

type OperacaoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sucesso       bool                   `protobuf:"varint,1,opt,name=sucesso,proto3" json:"sucesso,omitempty"`
	Resultado     map[string]string      `protobuf:"bytes,2,rep,name=resultado,proto3" json:"resultado,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperacaoResponse) Reset() {
	*x = OperacaoResponse{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperacaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperacaoResponse) ProtoMessage() {}

func (x *OperacaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperacaoResponse.ProtoReflect.Descriptor instead.
func (*OperacaoResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *OperacaoResponse) GetSucesso() bool {
	if x != nil {
		return x.Sucesso
	}
	return false
}

func (x *OperacaoResponse) GetResultado() map[string]string {
	if x != nil {
		return x.Resultado
	}
	return nil
}

func (x *OperacaoResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x03api\"f\n" +
	"\n" +
	"Requisicao\x12\x1f\n" +
	"\x04auth\x18\x01 \x01(\v2\t.api.AuthH\x00R\x04auth\x12+\n" +
	"\boperacao\x18\x02 \x01(\v2\r.api.OperacaoH\x00R\boperacaoB\n" +
	"\n" +
	"\bconteudo\"?\n" +
	"\x04Auth\x12\x19\n" +
	"\baluno_id\x18\x01 \x01(\tR\aalunoId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\xe1\x01\n" +
	"\bOperacao\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rnome_operacao\x18\x02 \x01(\tR\fnomeOperacao\x12=\n" +
	"\n" +
	"parametros\x18\x03 \x03(\v2\x1d.api.Operacao.ParametrosEntryR\n" +
	"parametros\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x1a=\n" +
	"\x0fParametrosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\bResposta\x121\n" +
	"\boperacao\x18\x01 \x01(\v2\x15.api.OperacaoResponseR\boperacao\"\xcc\x01\n" +
	"\x10OperacaoResponse\x12\x18\n" +
	"\asucesso\x18\x01 \x01(\bR\asucesso\x12B\n" +
	"\tresultado\x18\x02 \x03(\v2$.api.OperacaoResponse.ResultadoEntryR\tresultado\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x1a<\n" +
	"\x0eResultadoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B<Z:github.com/erikbayerlein/mult-protocol-clients/internal/pbb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_proto_goTypes = []any{
	(*Requisicao)(nil),       // 0: api.Requisicao
	(*Auth)(nil),             // 1: api.Auth
	(*Operacao)(nil),         // 2: api.Operacao
	(*Resposta)(nil),         // 3: api.Resposta
	(*OperacaoResponse)(nil), // 4: api.OperacaoResponse
	nil,                      // 5: api.Operacao.ParametrosEntry
	nil,                      // 6: api.OperacaoResponse.ResultadoEntry
}
var file_client_proto_depIdxs = []int32{
	1, // 0: api.Requisicao.auth:type_name -> api.Auth
	2, // 1: api.Requisicao.operacao:type_name -> api.Operacao
	5, // 2: api.Operacao.parametros:type_name -> api.Operacao.ParametrosEntry
	4, // 3: api.Resposta.operacao:type_name -> api.OperacaoResponse
	6, // 4: api.OperacaoResponse.resultado:type_name -> api.OperacaoResponse.ResultadoEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_client_proto_msgTypes[0].OneofWrappers = []any{
		(*Requisicao_Auth)(nil),
		(*Requisicao_Operacao)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
